### ISSUE TITLE
Error500 : Shortened urls don't work

### ISSUE THREAD

**Issue by quentinDupont** [YunoHost-Apps/lstu_ynh#10]
Hello,

The installation went well but when I try to use it to shorten an url, it send me to a 500 error screen.
Example : https://link.cloud117.fr/a

If someone has an any idea, it will be great :slightly_smiling_face: 

Thank you !

**Comment by frju365** [comment]
I'm trying to fix the problem. Normally it will be fixed in the next PR.

**Comment by quentinDupont** [comment]
Thanks a lot !

**Comment by maniackcrudelis** [comment]
Same for me, when I try to shorten a URL, I have a dinosaur throwing up a rainbow !
The upgrade to the current PR doesn't work, as well as a new installation from it.

**Comment by kay0u** [comment]
It should be fixed now.

**Comment by kay0u** [comment]
I close this issue, if you have any problem, don't hesitate to open a new one.
