### ISSUE TITLE
Cpan dependencies

### ISSUE THREAD

**Issue by grosbedos** [YunoHost-Apps/lstu_ynh#15]
Hi,

I can install this app with no errors, but when i create a short link, i have an error.
`Can't locate Image/PNG/QRCode.pm`

My debian need the package libpng-dev to install Image/PNG/QRCode.pm during the install of Carton with cpan.

Best regards.

**Comment by ldidry** [comment]
@frju365 Please have a look at https://framagit.org/luc/lstu/wikis/dependencies. Also, you can choose to not install some dependencies, making the installation faster: https://framagit.org/luc/lstu/wikis/installation#installation-of-lstu

**Comment by grosbedos** [comment]
Thanks for your answer.
Or just add libpng-dev at line 50 in the file scripts/install ?

`ynh_package_install build-essential libssl-dev libpq-dev libpng-dev`

Best regards

**Comment by ldidry** [comment]
My comment was for @frju365, for him to fix properly the package. Yes, adding libpng-dev to the packages installation is enough, but I was pointing him the doc to make a cleaner app.

**Comment by grosbedos** [comment]
Oh, i was sleeping i think ;)

**Comment by frju365** [comment]
Seems to be better for this point.
