### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by tituspijean** [YunoHost-Apps/lstu_ynh#16]
@toitoinebzh on IRC had a failed installation with no subsequent removal of the app. It left Nginx down.

[Log can be found here](https://framabin.org/p/?8ee86933768d2601#bZJqMfX5+jz6O3mZfEZhUY3nIlLQh/z32Ql+wWFJETc=)

**Comment by anto1ne** [comment]
some additional info

Debian 9.5 64bit (Linux 4.9.0-8-amd64)
yunohost    3.2.2 (stable)
yunohost-admin    3.2.1 (stable)
moulinette    3.2.0 (stable)
ssowat    3.2.0 (stable)

**Comment by kay0u** [comment]
This should be fixed. Reopen it if not
