### ISSUE TITLE
"./upgrade: ligne 45: CHECK_PATH : commande introuvable"

### ISSUE THREAD

**Issue by anto1ne** [YunoHost-Apps/lstu_ynh#17]
Hi,

My server fails when I try to update lstu. (please, have a look at line 85)
https://paste.yunohost.org/xipapovide

Here are some details about my server.

yunohost
    3.4.2.2 (stable)
yunohost-admin
    3.4.2 (stable)
moulinette
    3.4.2 (stable)
ssowat
    3.4.2 (stable)

**Comment by frju365** [comment]
C'est corrigé normalement. Merci d'avoir ouvert cette issue :wink:

**Comment by anto1ne** [comment]
Nouveau message d'erreur depuis ce matin

https://paste.yunohost.org/inediyuluy
https://paste.yunohost.org/uvedijimim.bash

**Comment by kay0u** [comment]
Peux-tu me donner le résultat de ça stp:
`systemctl status lstu`

**Comment by anto1ne** [comment]
Voilà le résultat 

```bash
admin@skynet:~$  systemctl status lstu
● lstu.service - Shortened URLs service
   Loaded: loaded (/etc/systemd/system/lstu.service; enabled; vendor preset: enabled)
   Active: active (running) (Result: exit-code) since Fri 2019-02-01 21:12:33 CET; 1 day 16h ago
     Docs: https://framagit.org/luc/lstu
  Process: 23518 ExecReload=/usr/local/bin/carton exec hypnotoad script/lstu (code=exited, status=255)
 Main PID: 1696 (/var/www/lstu/s)
    Tasks: 5 (limit: 4915)
   CGroup: /system.slice/lstu.service
           ├─1696 /var/www/lstu/script/lstu
           ├─1697 /var/www/lstu/script/lstu
           ├─1698 /var/www/lstu/script/lstu
           ├─1699 /var/www/lstu/script/lstu
           └─1700 /var/www/lstu/script/lstu
admin@skynet:~$ 
```

**Comment by kay0u** [comment]
`journalctl -xe` te dit quelque chose ?
Sinon c'est bizarre, je ne vois pas grand chose.

Essaye de faire

`systemctl stop lstu` jusqu'à ce qu'il te dise qu'il n'y a plus rien à arrêter, ensuite `systemctl start`, et enfin relance l'upgrade?...
