### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by anmol26s** [YunoHost-Apps/lstu_ynh#2]
Hi
I tried installing the app. But it fails with the error:

`Warning: /usr/share/yunohost/helpers.d/print: line 4: $1: unbound variable`

**Comment by frju365** [comment]
Hello,
Could you pls share your log if you have it ?
thanks,
frju365

**Comment by anmol26s** [comment]
Ok 
Now it works. I don't know why it gave that error last time.
Thanks
