### ISSUE TITLE
migration to 4.0 yunohost

### ISSUE THREAD

**Issue by changemenemo** [YunoHost-Apps/lstu_ynh#46]
arm olimex 2 board

```
  - Aug 02 01:55:04 carton[778]: ListUtil.c: loadable library and perl binaries are mismatched (got handshake key 0x9400080, needed 0x9380080)
  - Aug 02 01:55:04 systemd[1]: lstu.service: Main process exited, code=exited, status=1/FAILURE
```

**Comment by ldidry** [comment]
Note to maintainers of the package: this just need a remove of `local` directory then redo a `carton install` with the options previously used.

**Comment by changemenemo** [comment]
```
! Installing the dependencies failed: Module 'DBD::mysql' is not installed
! Bailing out the installation for Mojo-mysql-1.07.
! Installing the dependencies failed: Module 'Mojo::mysql' is not installed 
! Bailing out the installation for Minion-Backend-mysql-0.14.
```
any ideas?

**Comment by ldidry** [comment]
Try
```
which mariadb_config && cd $(dirname $(which mariadb_config)) && ln -s mariadb_config mysql_config && cd -
```

Then reinstall the dependencies.

That’s a long shot since I don’t know what caused the `DBD::mysql`’s installation failure.

**Comment by changemenemo** [comment]
non ça ne change rien.
Est-ce qu'on est sur que totues les dépendances sont dans debian 10 de ce qu'il faut pour cette app?

**Comment by ldidry** [comment]
Étant le développeur de Lstu, je peux répondre « Oui ». Il faudrait voir le log d’installation des modules.

Mais à la limite : OSEF. En effet, je viens d’aller voir comment est installé et configuré Lstu dans ce package et ça utilise une BDD PostgreSQL. Donc il suffit d’ajouter `--without=mysql` à `carton install --deployment` (j’avais oublié de préciser le `--deployment`).

Ah pis tant qu’à faire, la commande correcte est directement dans le [script d’installation](https://github.com/YunoHost-Apps/lstu_ynh/blob/master/scripts/install#L159) : `carton install --deployment --without=sqlite --without=mysql`

**Comment by changemenemo** [comment]
et si il ne réagit pas à l'existence de mariadb c'est qu'il n'est pas content de la version de mariadb je suppose?

**Comment by ldidry** [comment]
En l’absence de log, je ne peux pas dire ce qui cloche (il manque peut-être `libmariadb-dev` ?). Mais à la limite, on s’en fout, puisque le paquet YNH installe Lstu pour qu’il fonctionne avec PostgreSQL, pas MySQL.

Il faut faire `carton install --deployment --without=sqlite --without=mysql`, ça règlera le souci avec les drivers MySQL, puisque ça ne les installera pas.

**Comment by changemenemo** [comment]
YAY it worked ;)
et libmariadb-dev manquait en effet pour info
