### ISSUE TITLE
Use version 0.17-2

### ISSUE THREAD

**Issue by ldidry** [YunoHost-Apps/lstu_ynh#7]
Version 0.16 adds a lot of improvments

See the changelog from 0.09-2 (current used version) to 0.16: https://framagit.org/luc/lstu/tags

Please, read the [update page of the wiki](https://framagit.org/luc/lstu/wikis/update), there is a lot of changes from 0.09-2 (no need to install pg stuff if using SQLite anymore).

The configuration template has changed a lot too!

EDIT : please use 0.16-1

**Comment by ldidry** [comment]
It would be a good thing to read almost the entire wiki, since it didn't exist a week ago.

**Comment by ldidry** [comment]
Version 0.17-1 has been released.

Beware of CSP and X-* headers settings as it may interfer with YNH headers (I don't know if YNH adds headers). You can disable Lstu CSP and X-* headers by setting them to `''` in the configuration file.

**Comment by frju365** [comment]
Done
