### ISSUE TITLE
Impossible to update

### ISSUE THREAD

**Issue by croulibri** [YunoHost-Apps/lstu_ynh#8]
Hello,

I tried an update today and the log is : 

```
Impossible de mettre à jour lstu

./upgrade: ligne 12: .fonctions: Aucun fichier ou dossier de ce type

+ source .fonctions

+ set -eu

Exécution du script « /var/cache/yunohost/from_file/lstu_ynh-908d9f6e8afb252e03974788db6e0edd515e5247/scripts/upgrade »...

Vérification des paquets requis pour lstu...

Terminé

Extraction...

Téléchargement...

Mise à jour de l'application lstu...
```

:disappointed:

**Comment by toitoinebzh** [comment]
Hi,

I can not update lstu. 
https://paste.yunohost.org/xipapovide

Here are some details about my server.


yunohost
    3.4.2.2 (stable)
yunohost-admin
    3.4.2 (stable)
moulinette
    3.4.2 (stable)
ssowat
    3.4.2 (stable)

**Comment by kay0u** [comment]
I think it's fixed, can you confirm that?

**Comment by anto1ne** [comment]
Hi,

When I subscribed to this issue few weeks ago, I had a discussion on irc #yunohost and I finally decide to uninstall and reinstall the new version of lstu. So I can not check that this fix works for this older version of lstu.

However, today I had the opportunity to upgrade lstu and it worked. I think that you can close this bug.

Thank you for your work :-)

**Comment by kay0u** [comment]
Ok, I close this issue.

You're welcome!
